LOCAL_REFRESH_INTERVAL = 1
WEB_REFRESH_INTERVAL = 30

TIME_FORMAT = "%H:%M:%S"
DATE_FORMAT = "%Y-%m-%d"

HOME_ASSISTANT_URL = "https://example.com"
HOME_ASSISTANT_KEY = "ABCDEF"
HOME_ASSISTANT_TEMP_SENSOR = "sensor.my_room_temperature"
